//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_car
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int idOrder { get; set; }
        public Nullable<int> IdCar { get; set; }
        public string RentTime { get; set; }
        public string RentStatus { get; set; }
        public Nullable<int> idClient { get; set; }
        public string Summ { get; set; }
    
        public virtual Cars Cars { get; set; }
    }
}
